version: "3.9"
services:
  backend:
    build: ./backend
    env_file: ./.env
    ports: ["8080:8080"]
    volumes:
      - ./backend/app/data:/app/app/data
    depends_on: [redis]
  webapp:
    build: ./webapp
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8080
    ports: ["3000:3000"]
    depends_on: [backend]
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports: ["6379:6379"]