apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: screen2deck-data-pvc
  namespace: screen2deck
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
provisioner: kubernetes.io/gce-pd  # Change based on cloud provider
parameters:
  type: pd-ssd  # GCP SSD, adjust for AWS/Azure
  replication-type: regional-pd
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer