site_name: Screen2Deck Documentation
site_description: Advanced OCR system for Magic The Gathering cards
site_author: Screen2Deck Team
site_url: http://localhost:8088/docs

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - blog:
      blog_dir: blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - Configuration: getting-started/configuration.md
  - Architecture:
      - Overview: architecture/overview.md
      - OCR Pipeline: architecture/ocr-pipeline.md
      - Export Formats: architecture/export-formats.md
  - Blog:
      - blog/index.md
      - "How we reached 95% accuracy": blog/01-how-we-hit-95.md
  - API Reference:
      - Endpoints: api/endpoints.md
      - WebSocket: api/websocket.md
  - Testing:
      - E2E Tests: testing/e2e.md
      - Benchmarks: testing/benchmarks.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gbordes77/Screen2Deck
  
  version:
    provider: mike
    default: stable