name: e2e-online
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: e2e-online-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Playwright
        run: |
          npm ci || npm i
          npx playwright install --with-deps

      - name: Docker Compose Up
        run: |
          docker compose --profile core build backend webapp
          docker compose --profile core up -d redis postgres backend webapp

      - name: Wait backend
        run: |
          for i in {1..30}; do curl -fsS http://localhost:8080/health && exit 0 || sleep 2; done; exit 1

      - name: Run E2E ONLINE
        env:
          FRONT_URL: http://localhost:3000
        run: node tests/webapp.online.js