name: golden-exports
on:
  push:
  pull_request:

jobs:
  verify-exports:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Prepare backend env
        run: |
          cat > backend/.env.docker <<'ENV'
          DATABASE_URL=postgresql+psycopg://postgres:postgres@postgres:5432/screen2deck
          REDIS_URL=redis://redis:6379/0
          JWT_SECRET_KEY=ci-secret
          OCR_MIN_CONF=0.62
          ALWAYS_VERIFY_SCRYFALL=true
          FEATURE_TELEMETRY=false
          OTEL_SDK_DISABLED=true
          ENV

      - name: Start core services
        run: |
          docker compose --profile core up -d --build redis postgres backend

      - name: Wait for backend health
        run: |
          for i in {1..60}; do
            if curl -sf http://localhost:8080/health >/dev/null; then
              echo "Backend healthy!"; exit 0;
            fi
            sleep 2
          done
          echo "Backend did not become healthy in time" >&2
          docker compose logs backend
          exit 1

      - name: Run golden export tests
        env:
          EXPORT_BASE_URL: http://localhost:8080
        run: |
          python -m pip install --upgrade pip
          python tests/exports/run_golden_exports.py

      - name: Dump backend logs on failure
        if: failure()
        run: docker compose logs backend